eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8090

spring:
  profiles:
    active: local
    include: jwt, redis
  application:
    name: auth-server