server:
  port: 8000

spring:
  profiles:
    active: dev

springdoc:
  swagger-ui:
    urls:
      - name: auth
        url: /v3/api-docs/auth

management:
  tracing:
    sampling:
      probability: 1.0