eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8000

spring:
  profiles:
    include:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**, /api/users/**