server:
  port: 8000

spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8888

springdoc:
  swagger-ui:
    urls:
      - name: auth
        url: /v3/api-docs/auth

management:
  tracing:
    sampling:
      probability: 1.0