CREATE TABLE IF NOT EXISTS CHAT (
    ID SERIAL PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    CHATROOM_ID BIGINT NOT NULL,
    CONTENT VARCHAR(255) NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS CHATROOM (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS CHATROOM_USER (
    ID SERIAL PRIMARY KEY,
    CHATROOM_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);