CREATE TABLE IF NOT EXISTS CHAT (
    ID SERIAL PRIMARY KEY,
    CHATROOM_ID BIGINT NOT NULL,
    SENDER_ID BIGINT NOT NULL,
    RECEIVER_ID BIGINT NOT NULL,
    R_NICKNAME VARCHAR(10) NOT NULL,
    R_IMAGE_URL VARCHAR(255) NOT NULL,
    NICKNAME VARCHAR(10) NOT NULL,
    CONTENT VARCHAR(255) NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS CHATROOM (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS CHATROOM_USER (
    ID SERIAL PRIMARY KEY,
    CHATROOM_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);